name: ci

on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        if: steps.changes.outputs.docker == 'true'
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        if: steps.changes.outputs.docker == 'true'
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        if: steps.changes.outputs.docker == 'true'
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.TARGET_USERNAME }}
          password: ${{ secrets.TARGET_TOKEN }}
      - 
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            py:
              - 'docker/python-tools/**'
            clipper:
              - 'docker/stream-clipper/**'
              - 'docker/python-tools/**'
            aud:
              - 'docker/audd-pi/**'
            docker:
              - 'docker/audd-pi/**'
              - 'docker/stream-clipper/**'
              - 'docker/python-tools/**'
      -
        if: steps.changes.outputs.py == 'true'
        name: Build and push py
        uses: docker/build-push-action@v3
        with:
          context: ./docker/python-tools
          platforms: linux/amd64,linux/arm64
          push: true
          tags: registry.gitlab.com/jrdnrgrs/recordpi/python-tools
      -
        if: steps.changes.outputs.clipper == 'true'
        name: Build and push stream-clipper
        uses: docker/build-push-action@v3
        with:
          context: ./docker/stream-clipper
          platforms: linux/amd64,linux/arm64
          push: true
          tags: registry.gitlab.com/jrdnrgrs/recordpi/stream-clipper
      -
        if: steps.changes.outputs.aud == 'true'
        name: Build and push audd-pi
        uses: docker/build-push-action@v3
        with:
          context: ./docker/audd-pi
          platforms: linux/amd64,linux/arm64
          push: true
          tags: registry.gitlab.com/jrdnrgrs/recordpi/audd-pi