name: ci

on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.TARGET_USERNAME }}
          password: ${{ secrets.TARGET_TOKEN }}
      -
        name: Build and push py
        uses: docker/build-push-action@v3
        with:
          context: ./docker/python-tools
          platforms: linux/amd64,linux/arm64
          push: true
      -
        name: Build and push recordpi
        uses: docker/build-push-action@v3
        with:
          context: ./docker/python-tools
          platforms: linux/amd64,linux/arm64
          push: true